name: Deploying exp-api (xc)using docker
on:
  push:
    branches:
    - main
    paths-ignore:
    - 'api/**'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: deploying changes
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.BACKENDHOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd beckn-exp-apis
          git checkout main
          git pull
          SHORT_SHA=$(git rev-parse --short HEAD)
          docker build -t beckn-exp-apis:$SHORT_SHA .
          docker stop beckn-exp-apis
          docker rm beckn-exp-apis
          docker run -d -p 8082:8082 --name beckn-exp-apis beckn-exp-apis:$SHORT_SHA
          echo "printing docker image sha"
          docker images --no-trunc --quiet beckn-exp-apis:$SHORT_SHA
          curl --location --request GET 'https://api.experience.becknprotocol.io/v2/event/event-message' --header 'Access-Control-Allow-Origin: *'
